server:
  port: 8885
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: hi
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
